### PR TITLE
Update manual_habitat_classification.csv for ELKR

### PR DESCRIPTION
**Pull request by nickw-CWF**
Katherine reviewed the remaining maps in the Teck telemetry [report](https://www.teck.com/media/Upper-Fording-River-Westslope-Cutthroat-Trout-Population-Assessment-and-Telemetry-Project,-Final-Report-(December-2016).pdf) and georeferenced spawning and rearing habitat distribution to bcfishpass.streams.

She revised Nick O.'s original manual habitat classification, so I just replaced all the lines with Katherine's new ones.

### CODE REVIEW

**Comment by smnorris** [comment]
We don't currently support for an `overwintering` habitat type, those rows will not get loaded unless that is added first.

**Review by smnorris — COMMENTED** [review]
I could merge up to line 141 for now if we want an updated model run with these changes and the Erickson Creek fix.

**Comment by smnorris** [comment]
Alternatively we could just rename `overwintering` to `rearing` or `spawning` for now to ensure crossings below these streams are higher up in a prioritization.

**Comment by nickw-CWF** [comment]
I don't think these manual classifications will add anything to what we have modelled right now, so I am ok with not having them loaded until we discuss adding an overwintering habitat type.

I am more interested in deriving the stream gradient and MAD values for each stream segment in each habitat type to help refine the hab param thresholds.

**Pull request merged**
