### PR TITLE
BULK-Updates-2024-06-13

### PR DESCRIPTION
**Pull request by LauraB-CWF**
Updates to crossings incorrectly assigned as 'Passable'

### CODE REVIEW

**Comment by smnorris** [comment]
Thanks. 

I know there are definitely instances in BULK and perhaps other WCRPs where PSCIS barrier status fixes were applied based on the PSCIS comments and were a bit too generous in the interpretation.
But I don't see these two records in the fix table already, that is not the issue here.

PSCIS data indicates these are both habitat confirmations and PSCIS scoring assigns these as passable. PSCIS comments indicate there are other issues going on that are not captured by the scoring - the crossings do need attention/fixes.

I'm fine with switching these to `POTENTIAL` but for users comparing PSCIS data to bcfishpass data we need to be able to tell why and when the status was changed from what is assigned by PSCIS. Can you adjust the `notes` values for these?

I'll have to make adjustments to ensure that the notes that describe this change are included in various output tables - `crossings_vw`, `crossings_wcrp_vw` and the FPTWG extract - so the casual user can tell why barrier status in PSCIS and bcfishpass do not match. In hindsight, this should already have been done - we already have an extensive list of barrier status adjustments.

@NewGraphEnvironment @captainmarmot @nickw-CWF - any comments welcome. Barrier status for a given crossing in bcfishpass may not match PSCIS - even for a habitat confirmation. But going forward something in the crossings views will be added to note why this is the case.

**Comment by NewGraphEnvironment** [comment]
seems odd to me to make these changes. The PSCIS metrics were collected somewhat recently using standard protocols and the scores came out passable. There is detailed reporting here https://www.newgraphenvironment.com/fish_passage_bulkley_2020_reporting/appendix-197665-197664-3042-barren-creek.html

crossings were considered passable when assessed. Impacts on fish populations were related to highway maintenance dredging vs passability at that time. We did not have any indication that the railway was being dredged as per the photos or we would have noted that...

Might make sense to reassess and re-enter the data as collected but doing custom alterations in the office to override detailed field assessment data seems like a slippery slope to me...  

The detail needed to communicate what is being communicated with these edits (as Simon mentioned - more detail is needed to clarify) - unless I am missing something - IMO belongs outside of bcfishpass.  Options could be standalone reporting or perhaps a note in an [issue of the repo](https://github.com/NewGraphEnvironment/fish_passage_bulkley_2020_reporting/issues) that builds the report of potential edits that would help clear up some uncertainty.


also just noticed this within this same PR:

> 197017,PASSABLE,LNIC,LB,2024-04-09,"This is a ford, PSCIS barrier_status = UNKNOWN, edit existing record in fix table to PASSABLE"

There are many thousands of fords and I believe 99.9% of them are all barrier_status = UNKNOWN.  I wouldn't think we need to use `[data/user_pscis_barrier_status.csv](https://github.com/smnorris/bcfishpass/pull/519/commits/1ed77f0701aed45b443a03f73488a3fc3835bb0c#diff-1679957ccb61a5f7b077ceebe77c7bae545b94145cd4b532dfa805d2b887c848)` to adjust them..... This is already happening in the modelling. 

Also - of importance related to the last note - symbolizing fords as "passable" (equivalent to bridges) can be confusing in the field because when we role up on a ford that looks like a bridge on the maps surveyors may think they should reassess it so that bcfishpass and PSCIS has the latest data. This common "unknown" and "passable" symbology used to happen in the past but we rectified that so that now we have a different symbol for the crossing while the modelling recognizes "unknown" as equivalent to "passable"....

**Comment by smnorris** [comment]
I agree that barrier status divergence between bcfishpass and PSCIS should be minimal if any.

This is more of a question for @nickw-CWF @oakoppel-1 - can adjustments to PSCIS status be made in the reporting rather than directly in the bcfishpass crossings table? Or maybe we could apply these changes only in `crossings_wcrp_vw` for CWF planning use? 

There are currently ~1300 PSCIS barrier status adjustments but mostly in WCRP watersheds.

**Comment by smnorris** [comment]
I'm going to merge, this isn't an issue with the PR but with how bcfishpass handles this data generally.

**Comment by LauraB-CWF** [comment]
Hi,

Thank you for your feedback - I am still getting familiar with everything, so I appreciate these explanations. As of right now, when I make changes to the fix table, I am mostly getting them through different emails or excel files on SharePoint so there may have been miscommunication regarding the edits that should be made to these crossings.

Updates that were sent to me regarding 197664 and 197665 crossings:

  *   Update Barren Creek structures (197664 and 197665) to POTENTIAL barrier status using fix table

When I initially did the PSCIS review I read all the comments of associated PSCIS points to determine passability of the crossings, then applied those fixes to the table to make these crossings passable based on their PSCIS assessment. I am not entirely positive, but I think the WCRP team made the decision to classify any CBS as 'Potential' even if the PSCIS assessment indicates that its passable, so that's why these changes were made.  Here is a note from one of the WCRP meetings: The team concluded that barriers should not be called passable if they need more information (Data Deficient structures) and their PSCIS score / barrier status should remain until further information is gathered.  The team also agrees that keeping a record of this information would be helpful so the site can be revisited in the future.  Based on that note, I assume these structures are considered data deficient and the team wants to get more information about the crossings before classifying them as passable.

Updates that were sent to me regarding 197017 and 197018 crossings:

  *   1011302218 Mine Creek and 1011302231 Mine Creek are visibly fords on satellite imagery - check satellite imagery and update to OBS in fix table if confirmed. Check satellite imagery and update to OBS in fix table if confirmed. Ensure there is not already an entry in the fix table for this crossing.

Above, you can see that fix doesn't make sense because the reviewer mentions that the structure is clearly a ford in satellite imagery (this is confirmed), but to update the structure type to OBS. Because this doesn't make sense, I just updated the passability status to passable.  I will ask Nick M-W if this update is incorrect when he returns.

In the meantime, I will make notes of your comments and forward them to the team.

Thank you for your help and let me know if you have any questions.

Laura Bernardi
GIS Technician
***@***.***
350, promenade Michael Cowpland Drive, Kanata, ON K2M 2W1
1.877.599.5777 | 613.599.9594
CanadianWildlifeFederation.ca<http://www.canadianwildlifefederation.ca/?src=signature> | Federationcanadiennedelafaune.ca<http://www.federationcanadiennedelafaune.ca/?src=signature>

[seeds]<http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1&utm_source=signature&utm_medium=referral&utm_campaign=biod>

Let's celebrate Canada's biodiversity by planting pollinator-friendly seeds.
Request your free seeds ><http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1?utm_source=signature&utm_medium=email&utm_campaign=mmg>
---------------------------------------
Célébrons la biodiversité du Canada en plantant des semences favorables aux pollinisateurs.
Demandez vos semences gratuites ><http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1?utm_source=signature&utm_medium=referral&utm_campaign=biod&s_locale=fr_CA>

**Comment by smnorris** [comment]
Thanks @LauraB-CWF ! That all sounds good and your updates work well for what the WCRP team needs.

The remaining issue is more of a general bcfishpass usage/architecture question that is not hard to resolve - but will take a bit of work on my end. Discussion on that can move over to https://github.com/smnorris/bcfishpass/issues/521

**Review by smnorris — APPROVED** [review]

**Pull request merged**
