### PR TITLE
a few pscis xings matched to modelled xings

### PR DESCRIPTION
**Pull request by NewGraphEnvironment**

### CODE REVIEW

**Comment by smnorris** [comment]
Scripts fail to run with this update as each of these were already in the lookup (there is a unique constraint on the PSCIS id):
```
50095,,706880116,,
50090,,706879645,,
50110,,706872809,,
```
I'll have to take a look at the crossings to see what is going on.

**Comment by smnorris** [comment]
I've fixed - the old matching was wrong.
Either I made a mistake in what data got retained or the reviewer made an error, I'm not sure. 
But there may be more in ELKR where the lookup is forcing the match to the stream instead of the modelled crossing.

**Comment by NewGraphEnvironment** [comment]
I did notice some instances  where there was a “crossing” looking point on the stream and not at a road stream intersection.

**Comment by smnorris** [comment]
In ELKR there are 42 PSCIS crossings forced to match to a particular stream rather than a modelled crossing.
Worth reviewing.
```
select count(*) from bcfishpass.pscis_modelledcrossings_streams_xref where watershed_group_code = 'ELKR' and modelled_crossing_id is null and linear_feature_id is not null;
 count
-------
    42
```

**Comment by NewGraphEnvironment** [comment]
interestante

**Comment by smnorris** [comment]
Based on reviewing the first 3 I don't trust the data at all, they should all be revisited.

**Comment by NewGraphEnvironment** [comment]
@smnorris - a couple workflow questions big guy.

1. i think you maybe sent me a link to a doc about how we do the csv edits but I can't seem to find it... Send again if it exists?
2. I have a situation for a couple of crossings where a reviewer has previously reviewed a couple crossings but I have updates that tie them to modelled crossings (see screenshot).  Wondering if maybe I should track that this has been reviewed before somehow (ex. put in the notes that "previously reviewed by XXX" or add a column called 'reviewer_previous1' or something and transfer reviewer initials there....)? 

image

**Comment by smnorris** [comment]
Basic csv edit guide for the pscis - model - stream matching is here: https://github.com/smnorris/bcfishpass/tree/main/01_prep/02_pscis

Since we have all changes in version control and now have individual users applying them I don't think we need to worry about tracking that the crossing has been reviewed before.

@njohanley is reviewing the crossings listed in #65 - we should coordinate efforts if you're reviewing in Elk.

**Comment by NewGraphEnvironment** [comment]
Thanks! I am hoping to not look at the Elk anymore but would be good to know what comes of the NJO review.

**Pull request merged**
