### PR TITLE
psf

### PR DESCRIPTION
**Pull request by smnorris**
- note observations downstream in output streams table
- mod access models to cancel barriers below known spawning/rearing habitat 
- add known habitat locations within CCIRA watersheds (where it affects the access model)
- update species presence in CCIRA watersheds

### CODE REVIEW

**Review by NewGraphEnvironment — COMMENTED** [review]
please tell me we aren't blanket removing "barriers" from every database generated by bcfishpass because adult fish got into an area upstream at some point in history?  95% of the culverts we call barriers are not "barriers" to full sized salmon (an extremely common misconception about what the provincial methodology measures for..). If we start removing everything that a full sized adfulvial fish can move through we have a completely different tool on our hands. The connectivity puzzle to date in my mind has mostly been related to younger life stages and timing of migration......

this might be a good catalyst for starting to "Refine barrier thresholds for road-stream crossing structures to explore metrics specific to life stage and life history types of species of interest. " which is a recommendation in every report from the last few years (ex. https://www.newgraphenvironment.com/fish_passage_skeena_2021_reporting/recommendations.html )

**Comment by smnorris** [comment]
If there are >= 5 FISS observations of salmon/steelhead since 1990 upstream, a stream is considered free of natural barriers / potentially accessible to those species.

For WCT/BT models, just one observation will cancel a downstream natural barrier.

**Comment by NewGraphEnvironment** [comment]
Oh- you are talking about "natural barriers" - not culverts!! ok - that makes sense

**Comment by NewGraphEnvironment** [comment]
phew

**Pull request merged**
