### PR TITLE
LNIC_Update2_2024-07-29

### PR DESCRIPTION
**Pull request by LauraB-CWF**
Updates to habitat based on PSE data.

### CODE REVIEW

**Review by smnorris — COMMENTED** [review]
A few requests:
- species codes need to be ALL CAPS
- your initials should be CAPS as well just for consistency
- I know there is lots of other data in here with measures to 6 decimal place precision, but this is meaningless - rounding to nearest integer is preferred

**Comment by nickw-CWF** [comment]
> A few requests:
> 
> * species codes need to be ALL CAPS
> * your initials should be CAPS as well just for consistency
> * I know there is lots of other data in here with measures to 6 decimal place precision, but this is meaningless - rounding to nearest integer is preferred

Do you want these resolved before merging this PR?

**Comment by smnorris** [comment]
> > A few requests:
> > 
> > * species codes need to be ALL CAPS
> > * your initials should be CAPS as well just for consistency
> > * I know there is lots of other data in here with measures to 6 decimal place precision, but this is meaningless - rounding to nearest integer is preferred
> 
> Do you want these resolved before merging this PR?

Preferably - but I can make the updates if required. 
The species code is the only one that is critical, the update won't work unless that is fixed.

**Comment by LauraB-CWF** [comment]
Hi Simon,

Thank you for your feedback, and sorry about these errors.

I had copied them from a separate file and didn't realize everything was formatted as it was.

I will fix this now, thank you for your patience.

Laura Bernardi
GIS Technician
***@***.***
350, promenade Michael Cowpland Drive, Kanata, ON K2M 2W1
1.877.599.5777 | 613.599.9594
CanadianWildlifeFederation.ca<http://www.canadianwildlifefederation.ca/?src=signature> | Federationcanadiennedelafaune.ca<http://www.federationcanadiennedelafaune.ca/?src=signature>

[seeds]<http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1&utm_source=signature&utm_medium=referral&utm_campaign=biod>

Let's celebrate Canada's biodiversity by planting pollinator-friendly seeds.
Request your free seeds ><http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1?utm_source=signature&utm_medium=email&utm_campaign=mmg>
---------------------------------------
Célébrons la biodiversité du Canada en plantant des semences favorables aux pollinisateurs.
Demandez vos semences gratuites ><http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1?utm_source=signature&utm_medium=referral&utm_campaign=biod&s_locale=fr_CA>

**Comment by smnorris** [comment]
> Thank you for your feedback, and sorry about these errors. I had copied them from a separate file and didn't realize everything was formatted as it was. I will fix this now, thank you for your patience

Not a problem! Thanks for making the fixes.

**Comment by LauraB-CWF** [comment]
Closing pull request.  Attributes formatted incorrectly.

**Pull request closed without merging**
