### PR TITLE
Bulkley Habitat Updates

### PR DESCRIPTION
**Pull request by LauraB-CWF**

### CODE REVIEW

**Comment by smnorris** [comment]
Looks like something is off in the csv formatting. Let me know if you'd like me to take a closer look, the diff is so big it doesn't render in github.

**Comment by LauraB-CWF** [comment]
Hi Simon,

Yes, I would appreciate that.

Should I send you the changes I am trying to commit?

Thank you,


Laura Bernardi
GIS Technician
***@***.***
350, promenade Michael Cowpland Drive, Kanata, ON K2M 2W1
1.877.599.5777 | 613.599.9594
CanadianWildlifeFederation.ca<http://www.canadianwildlifefederation.ca/?src=signature> | Federationcanadiennedelafaune.ca<http://www.federationcanadiennedelafaune.ca/?src=signature>

[seeds]<http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1&utm_source=signature&utm_medium=referral&utm_campaign=biod>

Let's celebrate Canada's biodiversity by planting pollinator-friendly seeds.
Request your free seeds ><http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1?utm_source=signature&utm_medium=email&utm_campaign=mmg>
---------------------------------------
Célébrons la biodiversité du Canada en plantant des semences favorables aux pollinisateurs.
Demandez vos semences gratuites ><http://donate.cwf-fcf.org/site/Donation2?df_id=7440&mfc_pref=T&7440.donation=form1?utm_source=signature&utm_medium=referral&utm_campaign=biod&s_locale=fr_CA>

**Comment by smnorris** [comment]
No, I can grab the PR - thanks!

**Comment by smnorris** [comment]
It looks like the change is new trailing commas on each line - basically a new empty column.
Remove that column/trailing commas and all should be good.

**Comment by smnorris** [comment]
deleting in favour of #509

**Pull request closed without merging**
