### PR TITLE
Added migration folder v0.5.3

### PR DESCRIPTION
**Pull request by andrewp-CWF**
Folder includes join_tracking_table_crossings_view.sql and migrate.sh

Pull request also includes additional wcrp column in wcrp_watersheds.csv

### CODE REVIEW

**Comment by andrewp-CWF** [comment]
I added in the wcrp column and run the function, so the views are in the wcrp schemas

**Comment by andrewp-CWF** [comment]
Hey Simon, was this merged and applied to the BC db?

**Comment by smnorris** [comment]
No, the migration doesn't run as is. Can you make the changes?

**Comment by andrewp-CWF** [comment]
I can make the changes,

It seems to be failing when it tries to load the wcrp_watersheds.csv into the testing database with the extra columns. Where would I be able to alter that table? I don't think I have access to bcfishpass_test

**Comment by andrewp-CWF** [comment]
Sounds good, I have just pushed the changes to the branch

**Pull request merged**
