### PR TITLE
Auto rank integration

### PR DESCRIPTION
**Pull request by andrewp-CWF**
- Created output table in db\bcfishpass\tables\wcrp.sql for barrier rankings
- Created 1 script per watershed to populate the output table in db\bcfishpass\reports

### CODE REVIEW

**Review by smnorris — COMMENTED** [review]
I'm wondering if this could be done with a single script. Is there unique logic in each different ranking file/area of interest?

**Comment by andrewp-CWF** [comment]
The only change is in the condition specifying the watershed so it could probably all go in one script.
I am wondering then, was it better to have all the where clauses for each wcrp commented out and then when it needs to be run, the user uncomments the clause for the wcrp they want to rank, or is there a more user-friendly way to selectively run the script for a specific watershed?

**Comment by smnorris** [comment]
It depends on the potential study area. If ranking is always within a given watershed, input parameters like `watershed code` / `local code` (or `blue_line_key` / `downstream_route_measure`) could be used.  
If reporting on full watershed groups, this breaks down because they are not all watersheds - particularly coastal but there are other exceptions too. I think most existing WCRPs are fine though.

But I should look more closely at the queries, I haven't familiarized myself with what they are doing yet.

Another thing to keep in mind is that these do not need to be pure sql - a python script would work fine and R should work too (R would require more setup but may be handy given the number of R users).

**Comment by andrewp-CWF** [comment]
Sounds good, I will make some changes and put it into one script

**Comment by smnorris** [comment]
One more comment - for crossings in the Elk River watershed you'll want to use the various `wct` columns for stats, not the salmon (`ch_cm_co_pk_sk`) columns.

**Pull request closed without merging**
