### PR TITLE
whse_basemapping.fwa_stream_networks_sp vs bcfishpass.streams

### PR DESCRIPTION
**Pull request by NewGraphEnvironment**
hashed out the `s.segmented_stream_id` lines. they could just be removed....

### CODE REVIEW

**Comment by smnorris** [comment]
I think you were right to ask about the memory - processing 1 watershed group appears to be about 10s (ADMS, 406 records). I'm testing with the same method as for precip - process and load each group one by one.

**Comment by smnorris** [comment]
I thought I had tested provincially but perhaps it was only the CWF target watersheds.

**Comment by smnorris** [comment]
It is still pretty slow, I'll modify to run the load in parallel.

**Comment by NewGraphEnvironment** [comment]
🥽

**Comment by smnorris** [comment]
~14min to load BC on my system running it in parallel.

**Pull request merged**
